### ISSUE TITLE
Please remove the margins around the buttons

### ISSUE THREAD

**Issue by Austint30** [danielkza/Gnome-Shell-Window-Buttons-Extension#12]
The whole reason why I wanted window buttons within the top bar is so I could easily close maximized apps just by flinging my mouse to the top-right corner. This extension, for some reason, has a margin above the top of the window buttons which means I have to aim my cursor around the X button to close the app.

Please remove margin above the window buttons. Try using padding or something instead. It would really improve the usability of this extension.

**Comment by kennethso168** [comment]
I have a hacky workaround by playing with the CSS of the themes. Go to `~/.local/share/gnome-shell/extensions/window_buttons@biox.github.com/themes/<your current theme>` and edit the style.css file.
For example, this is the beginning part of the default theme:
```CSS
/* The box-bin element holds the button-box element which holds each window-button.
 *
 * Control spacing between each button via .button-box.
 */
.box-bin { 
    border-width: 0px;
    padding: 0px;
    margin: 0px;
}

.button-box {
    spacing: 4px;
}

/* The style for each individual window button */
.window-button {
    width: 24px;
    height: 20px;
}
```
By using the looking class, I find that the `.box-bin` element's height is 30px, but the `.window-button` is only 20px tall, so there is some dead space at the top.
A temporary workaround is to simply increase the height of `.window-button` to **30px**.
It's hacky, and I think a more proper solution is to really look into padding or the like. You may also need to adapt it to your own chosen theme. I'm also not sure if it works for other panel sizes, if any (not familiar with gnome).
And I agree this is an important aspect of usability so I wish @danielkza can have a look and fix it.
